using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocParseLab.Server.Migrations
{
    /// <inheritdoc />
    public partial class DocumentDigitalSignatures : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "DocumentSignatures" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DocumentId" integer NOT NULL,
                    "SignedByUserId" integer NOT NULL,
                    "TextHashSha256" text NOT NULL,
                    "SignedAt" timestamp with time zone NOT NULL,
                    "SignerEmailSnapshot" text NOT NULL,
                    "SignerDisplayNameSnapshot" text,
                    "SignerRoleSnapshot" text NOT NULL,
                    "Comment" text,
                    "SignatureKind" text NOT NULL,
                    CONSTRAINT "PK_DocumentSignatures" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DocumentSignatures_ParsedDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "ParsedDocuments" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_DocumentSignatures_Users_SignedByUserId" FOREIGN KEY ("SignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_DocumentSignatures_DocumentId_SignedAt" ON "DocumentSignatures" ("DocumentId", "SignedAt");
                CREATE INDEX IF NOT EXISTS "IX_DocumentSignatures_SignedByUserId" ON "DocumentSignatures" ("SignedByUserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DocumentSignatures");
        }
    }
}
