using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DocParseLab.Server.Migrations
{
    /// <inheritdoc />
    public partial class OfficeInformationSystem : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Идемпотентно: DocumentVersions могла остаться от AddDocxAndVersions, если RemoveDocumentVersions не применялась.
            migrationBuilder.Sql("""
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "DepartmentId" integer;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "DisplayName" text;
                ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "Role" text NOT NULL DEFAULT 'Employee';

                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "CurrentApproverUserId" integer;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "DepartmentId" integer;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "DocumentType" text NOT NULL DEFAULT 'general';
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "ResponsibleUserId" integer;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "SubmittedAt" timestamp with time zone;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "Tags" text;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "Title" text;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "WorkflowComment" text;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "WorkflowCompletedAt" timestamp with time zone;
                ALTER TABLE "ParsedDocuments" ADD COLUMN IF NOT EXISTS "WorkflowStatus" text NOT NULL DEFAULT 'Draft';

                UPDATE "ParsedDocuments" SET "WorkflowStatus" = 'Draft' WHERE "WorkflowStatus" IS NULL OR "WorkflowStatus" = '';
                UPDATE "ParsedDocuments" SET "DocumentType" = 'general' WHERE "DocumentType" IS NULL OR "DocumentType" = '';
                UPDATE "Users" SET "Role" = 'Employee' WHERE "Role" IS NULL OR "Role" = '';
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Departments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "DocumentVersions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DocumentId" integer NOT NULL,
                    "VersionNumber" integer NOT NULL,
                    "Text" text NOT NULL,
                    "ChangeType" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "CreatedByUserId" integer,
                    CONSTRAINT "PK_DocumentVersions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DocumentVersions_ParsedDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "ParsedDocuments" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_DocumentVersions_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "DocumentWorkflowHistory" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DocumentId" integer NOT NULL,
                    "UserId" integer,
                    "Action" text NOT NULL,
                    "Comment" text,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_DocumentWorkflowHistory" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DocumentWorkflowHistory_ParsedDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "ParsedDocuments" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_DocumentWorkflowHistory_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Users_DepartmentId" ON "Users" ("DepartmentId");
                CREATE INDEX IF NOT EXISTS "IX_ParsedDocuments_CurrentApproverUserId" ON "ParsedDocuments" ("CurrentApproverUserId");
                CREATE INDEX IF NOT EXISTS "IX_ParsedDocuments_DepartmentId" ON "ParsedDocuments" ("DepartmentId");
                CREATE INDEX IF NOT EXISTS "IX_ParsedDocuments_ResponsibleUserId" ON "ParsedDocuments" ("ResponsibleUserId");
                CREATE INDEX IF NOT EXISTS "IX_ParsedDocuments_WorkflowStatus" ON "ParsedDocuments" ("WorkflowStatus");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Departments_Name" ON "Departments" ("Name");
                CREATE INDEX IF NOT EXISTS "IX_DocumentVersions_CreatedByUserId" ON "DocumentVersions" ("CreatedByUserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DocumentVersions_DocumentId_VersionNumber" ON "DocumentVersions" ("DocumentId", "VersionNumber");
                CREATE INDEX IF NOT EXISTS "IX_DocumentWorkflowHistory_CreatedAt" ON "DocumentWorkflowHistory" ("CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_DocumentWorkflowHistory_DocumentId" ON "DocumentWorkflowHistory" ("DocumentId");
                CREATE INDEX IF NOT EXISTS "IX_DocumentWorkflowHistory_UserId" ON "DocumentWorkflowHistory" ("UserId");
                """);

            migrationBuilder.Sql("""
                DO $EF$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ParsedDocuments_Departments_DepartmentId') THEN
                        ALTER TABLE "ParsedDocuments" ADD CONSTRAINT "FK_ParsedDocuments_Departments_DepartmentId"
                            FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ParsedDocuments_Users_CurrentApproverUserId') THEN
                        ALTER TABLE "ParsedDocuments" ADD CONSTRAINT "FK_ParsedDocuments_Users_CurrentApproverUserId"
                            FOREIGN KEY ("CurrentApproverUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ParsedDocuments_Users_ResponsibleUserId') THEN
                        ALTER TABLE "ParsedDocuments" ADD CONSTRAINT "FK_ParsedDocuments_Users_ResponsibleUserId"
                            FOREIGN KEY ("ResponsibleUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Departments_DepartmentId') THEN
                        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Departments_DepartmentId"
                            FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL;
                    END IF;
                END $EF$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Users" DROP CONSTRAINT IF EXISTS "FK_Users_Departments_DepartmentId";
                ALTER TABLE "ParsedDocuments" DROP CONSTRAINT IF EXISTS "FK_ParsedDocuments_Users_ResponsibleUserId";
                ALTER TABLE "ParsedDocuments" DROP CONSTRAINT IF EXISTS "FK_ParsedDocuments_Users_CurrentApproverUserId";
                ALTER TABLE "ParsedDocuments" DROP CONSTRAINT IF EXISTS "FK_ParsedDocuments_Departments_DepartmentId";

                DROP TABLE IF EXISTS "DocumentWorkflowHistory";
                DROP TABLE IF EXISTS "DocumentVersions";
                DROP TABLE IF EXISTS "Departments";

                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "WorkflowStatus";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "WorkflowCompletedAt";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "WorkflowComment";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "Title";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "Tags";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "SubmittedAt";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "ResponsibleUserId";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "DocumentType";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "DepartmentId";
                ALTER TABLE "ParsedDocuments" DROP COLUMN IF EXISTS "CurrentApproverUserId";

                ALTER TABLE "Users" DROP COLUMN IF EXISTS "Role";
                ALTER TABLE "Users" DROP COLUMN IF EXISTS "DisplayName";
                ALTER TABLE "Users" DROP COLUMN IF EXISTS "DepartmentId";
                """);
        }
    }
}
